### PR TITLE
Added NPM package.json.

### PR DESCRIPTION
**Pull request by leighmcculloch**
Added NPM package.json.

As requested by @mef in robflaherty/jquery-scrolldepth#74

### CODE REVIEW

**Comment by leighmcculloch** [comment]
@mef I'm not very experienced with npm package.json files. Does this meet all the requirements?

**Comment by mef** [comment]
@leighmcculloch Thanks!

A comma is missing at the end of line 5, making the JSON invalid.

``` shell
$ npm install git://github.com/leighmcculloch/gascrolldepth.js.git#add-npm-package.json
# (...)
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Unexpected token 'r' at 6:4

```

**Comment by leighmcculloch** [comment]
@mef Fixed. How are we looking now?

**Comment by mef** [comment]
I'm afraid there's a trailing comma at the end of line 10, preventing the file to parse correctly.

**Comment by mef** [comment]
Rest of the file is good, I have checked :)

**Comment by leighmcculloch** [comment]
@mef Oh dear, thank you for your patience! I don't use npm much and I'm sick in bed so I thought I'd just wing it. I just actually tested it this time and it should be good now.

**Comment by mef** [comment]
Thank you so much! 

I confirm that it works well now :)

**Pull request merged**
