### PR TITLE
Feature/custom mark

### PR DESCRIPTION
**Pull request by heavybeard**
I add 2 more keys on `extends` obj:
- `markGap` abilitate the user to select custom percentage gap
- `customMarks` abilitate the user to select custom marks in and Array

The source script in index is now fixed

### CODE REVIEW

**Comment by leighmcculloch** [comment]
@heavybeard did you want to open this PR on the https://github.com/robflaherty/jquery-scrolldepth/ repository which is the source? This fork I'm maintaining is going to continue to track `jquery-scrolldepth`, except remove the dependency on jquery.

**Comment by heavybeard** [comment]
Ok @leighmcculloch, it's a good idea. Thanks!

**Comment by leighmcculloch** [comment]
Closing because @heavybeard will open it on the source.

**Comment by heavybeard** [comment]
This is the new PR on the original source https://github.com/robflaherty/jquery-scrolldepth/pull/81

**Pull request closed without merging**
